stages:
  - build
  - test

build:
  stage: build
  script:
    - gradle build
  tags:
    - gradle
    - java
    - linux

test:
  stage: test
  script:
    - java ./test/TestRunner
  tags:
    - java
    - linux
